config/routes.rb
StripeTest::Application.routes.draw do
  resources :purchases, only: [:new, :create]
  mount StripeEvent::Engine => '/stripe-webhooks'

  root to: 'purchases#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
  end

  def create
    stripe_service = PurchasesService.new(params)
    result = stripe_service.charge
    status = result.has_key?(:error) && :unprocessable_entity || :ok
    render json: result, status: status
  end

end

app/views/application/_javascripts.html.haml
= javascript_include_tag 'application'
= yield :scripts

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stripe Test
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    .wrapper
      %header#main-header
        = render 'header'

      %main#main-container
        = yield

    %footer#main-footer
      .wrapper
        = render 'footer'

    = render 'javascripts'

app/views/purchases/_billing_address_fields.html.haml
%fieldset#billing-address
  %legend Billing Address

  .address
    %label Address Line1:
    = text_field_tag 'billing_address[address_line1]', '',
      data: { stripe: 'address_line1' }
    %br

    %label Address Line2:
    = text_field_tag 'billing_address[address_line2]', '',
      data: { stripe: 'address_line2' }
    %br

    %label City:
    = text_field_tag 'billing_address[address_city]', '',
      data: { stripe: 'address_city' }
    %br

    %label State:
    = text_field_tag 'billing_address[address_state]', '',
      data: { stripe: 'address_state' }
    %br

    %label Zip:
    = text_field_tag 'billing_address[address_zip]', '',
      data: { stripe: 'address_zip' }
    %br

app/views/purchases/_shipping_address_fields.html.haml
%fieldset#shipping-address
  %legend
    Shipping Address
    %label
      = check_box_tag 'same_as_billing', false
      %small ( check if different )

  .address
    %label Address Line1:
    = text_field_tag 'shipping_address[address_line1]', ''
    %br

    %label Address Line2:
    = text_field_tag 'shipping_address[address_line2]', ''
    %br

    %label City:
    = text_field_tag 'shipping_address[address_city]', ''
    %br

    %label State:
    = text_field_tag 'shipping_address[address_state]', ''
    %br

    %label Zip:
    = text_field_tag 'shipping_address[address_zip]', ''
    %br

- content_for :scripts do
  :javascript
    $(document).ready(function(){
      new stripeTest.ShippingActivator($('#shipping-address'), $('#same_as_billing'))
    });

app/views/purchases/new.html.haml
%section
  %h1 Panda Product:

  %h2 Price: $1,000.00

  %div
    %strong Contents:
    %ul
      %li Awesomeness
      %li Attractiveness


  = form_tag purchases_path, id: 'payment-form' do
    -# Reference fields: As this is an example app, these hidden values are just for
    -# show how can we send different values for products (this logic should go
    -# on another place :p)
    = hidden_field_tag :amount, 100000
    = hidden_field_tag :description, 'Panda Product'

    .card
      %label Contact Email:
      = email_field_tag :email, '', placeholder: 'your@email.com'

      %label Credit Card Number:
      = text_field_tag 'number', '', data: { stripe: 'number' }

      %label Name on Credit Card:
      = text_field_tag 'billing_address[name]', '', data: { stripe: 'name' }

      %label Security Code
      = text_field_tag 'cvc', '', data: { stripe: 'cvc' }

      %label Expiration Date:
      = select_month Date.today,
        { add_month_numbers: true, use_short_month: true },
        data: { stripe: 'exp-month'}
      = select_year Date.today,
        { end_year: 2050 },
        data: { stripe: 'exp-year' }

    = render 'billing_address_fields'

    = render 'shipping_address_fields'

    = submit_tag 'Purchase', class: 'btn center'

- content_for :scripts do
  :javascript
    $(document).ready(function(){
      new stripeTest.Payment({
        stripeKey: "#{STRIPE_PUBLIC_KEY}",
        form: $('#payment-form')
      });
    });